console: Fix traceback when switching to fullscreen
Traceback (most recent call last):
  File "/home/crobinso/src/virt-manager/virtManager/details.py", line 1257, in switch_page
    self.console.details_refresh_can_fullscreen()
  File "/home/crobinso/src/virt-manager/virtManager/console.py", line 965, in details_refresh_can_fullscreen
    return self._refresh_can_fullscreen()
  File "/home/crobinso/src/virt-manager/virtManager/console.py", line 464, in _refresh_can_fullscreen
    self.widget("control-fullscreen").set_sensitive(allow_fullscreen)
TypeError: Argument 1 does not allow None as a value