error: Make sure we set proper transient parent
We were using widget.parent, which is the parent container widget (if
present), not the dialog transient parent.